management:
  server:
    port: 9003

logging:
  config: classpath:log4j2-spring.xml
  level:
    root: info
    sql: info
    web: info

spring:
  threads:
    virtual:
      enabled: false

---
message:
  period: 180
  suffix: server break down
  channels:
    - platform: telegram
      open-flag: 1
      app-id:
      app-secret: telegram bot token
      chat-id: "-100123"
    - platform: lark
      open-flag: 0
      app-id: cli_xxx
      app-secret: xxx
      chat-id: ou_xxx

---
remote:
  servers:
    - name: server1
      open-flag: 1
      addr: http://127.0.0.1:8080/hello
      period: 10000
      timeout: 5000
      fail-count: 5
    - name: server2
      open-flag: 0
      addr: http://127.0.0.1:8081/hello
      period: 5000
      timeout: 3000
      fail-count: 5